######################################################################
# Automatically generated by qmake (3.1) Tue May 29 08:36:34 2018
######################################################################

TEMPLATE = app
QT+= widgets network
TARGET = using_iodevice
DEFINES += QT_DEPRECATED_WARNINGS
SOURCES += main.cpp
include(../../qtnetworkng.pri)
