#ifndef QTNG_CONFIG_H
#define QTNG_CONFIG_H

#ifndef QTNETWORKNG_NAMESPACE
#  define QTNETWORKNG_NAMESPACE qtng
#endif

#define QTNETWORKNG_NAMESPACE_BEGIN namespace QTNETWORKNG_NAMESPACE {
#define QTNETWORKNG_NAMESPACE_END }

#define QTNG_VERSION 1.0.0

#endif  // QTNG_CONFIG_H
